# Generated by Django 5.1.4 on 2025-01-03 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        ('app2', '0003_remove_course_student_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='direction',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app2.course'),
        ),
    ]
