# Generated by Django 5.1.4 on 2025-01-03 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_direction_student_last_name_student_course'),
        ('app2', '0003_remove_course_student_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.course'),
        ),
    ]
