# Generated by Django 5.1.4 on 2025-01-03 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Course',
        ),
    ]
