# Generated by Django 5.1.4 on 2025-01-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_curso_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Description not available'),
        ),
    ]
